events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for" '
                    'req_id="$request_id"'; 
                    
    access_log /var/log/nginx/access.log main;

    server {
        listen 80;

<<<<<<< Updated upstream
        # Chuyển hướng các request bắt đầu bằng /api/auth/ vào IAM Service
=======
        location / {
            root /usr/share/nginx/html;
            index login.html index.html;
            try_files $uri $uri/ /login.html; 
            add_header X-Request-ID $request_id always;
        }

>>>>>>> Stashed changes
        location /api/auth/ {
            proxy_pass http://iam-service:3001/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Request-ID $request_id;
            add_header X-Request-ID $request_id always;
        }
    }
}