worker_processes 1;

events { worker_connections 1024; }

http {
    sendfile on;

    # Cấu hình Upstream trỏ tới các service
    upstream frontend {
        server frontend:3000;
    }
    upstream iam_service {
        server iam-service:3001;
    }

    server {
        listen 80;

        # Chuyển hướng các request bắt đầu bằng /api/auth/ vào IAM Service
        location /api/auth/ {
            proxy_pass http://iam_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Mặc định đẩy về Frontend
        location / {
            proxy_pass http://frontend/;
        }
    }
}